### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by Yolokos** [GetRektBoy724/SharpHalos#1]
Hi, I'm learning new techniques to develop a malvare, I tried different implementations step by step research every line of the code, debugging and etc. I saw your solution and I like it. It looks great, beatiful. But I don't understand when we check StubIntegrity down up, why did you use this formula? what is it meaning? 
for (int z = 1; z < 50; z++) {
     Copy((FunctionAddress + (-32 * z)), ref FunctionOpcode, 0, 24); 
Why -32, +32 and why 50 times? I searched, I read different topics but I didn't found any explanation of this.

**Comment by GetRektBoy724** [comment]
Hi @Yolokos ! SharpHalos works by checking the neighboring NT function's syscall index, hence why it scans the up and down neighbors. 32 is the size of a complete syscall stub, and I use the Copy function to read the unmanaged memory to a managed buffer, then I use the CheckStubIntegrity function to check if that neighboring syscall stub is altered or not. I use 50 as the limit of the scan for the neighboring NT function

**Comment by Yolokos** [comment]
Hi @GetRektBoy724, thank you for your answer, I have one more) For example, we are searching NtAllocateVirtualMemory in ntdll library using PE headers, but this func was hooked by EDR. We are starting search another func without hook, and we found it, but it wasn't NtAllocateVirtualMemory. For example it was func called as NtAlertResumeThread, and the main question How we can use another func, if we searched NtAllocateVirtualMemory? Why are we searching func such as NtAllocateVirtualMemory if we can use any another func? If we have syscall number without hook, can we replace funcs like NtAllocateVirtualMemory with NtAlertResumeThread, or can't we? Could you explain pls, if you have time. <3
